# This is a basic workflow to help you get started with Actions

name: Publish Website
permissions:
  contents: write
# Controls when the workflow will run
on:
  pull_request:
    branches: 
     - "main"

  push:
    branches: 
     - "main"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: wasm-pack-action
        uses: jetli/wasm-pack-action@v0.4.0
      - name: Build pkg
        run: >-
          cd browser
          && wasm-pack build --target web --no-pack --release
      - name: Install and run oranda
        run: >-
          echo "# Live Example" > ./live-preview.md
          && curl --proto '=https' --tlsv1.2 -LsSf https://github.com/axodotdev/oranda/releases/latest/download/oranda-installer.sh | sh
          && oranda build
      - name: Move wasm-pack output and index.html
        run: >-
          rm ./browser/pkg/.gitignore
          && rm ./public/live-preview.md
          && mkdir ./public/live-preview
          && cp -r ./browser/pkg/* ./public/live-preview/
          && cp -r ./browser/index.html ./public/live-preview/
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - name: PR upload
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./public/*
